version: '3'
services:
  app: # docker-compose exec app bash -> composer install && mv .env.example .env && php artisan key:generate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: bfc1eea2-196f-4d80-b357-29629bec82b5
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_size=1G --join_buffer_size=512M --sort_buffer_size=128M --read_rnd_buffer_size=128M
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: bfc1eea2-196f-4d80-b357-29629bec82b5
    # volumes:
    #   - ./sql:/docker-entrypoint-initdb.d
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
